image: maven:3.8.7-eclipse-temurin-19

stages:          
  - build
  - test

build-job:       
  stage: build
  script:
    - mvn compile
  artifacts:
    paths:
      - target

test-job:
  stage: test
  script:
    - mvn test